const quizData = [
{ symptom: "chestPain", specialty: "Cardiovascular Medicine", confidence: "0.9"},
{ symptom: "chestPain", specialty: "Pulmonary Medicine", confidence: "0.4"},
{ symptom: "chestPain", specialty: "Gastroenterology", confidence: "0.3"},
{ symptom: "chestPain", specialty: "Contact Centre", confidence: "1.0"},
{ symptom: "shortnessOfBreath", specialty: "Pulmonary Medicine", confidence: "0.9"},
{ symptom: "shortnessOfBreath", specialty: "Cardiovascular Medicine", confidence: "0.8"},
{ symptom: "shortnessOfBreath", specialty: "Emergency Medicine", confidence: "1.0"},
{ symptom: "abdominalPain", specialty: "Gastroenterology", confidence: "0.9"},
{ symptom: "abdominalPain", specialty: "General Surgery", confidence: "0.7"},
{ symptom: "abdominalPain", specialty: "Gynecology", confidence: "0.4"},
{ symptom: "abdominalPain", specialty: "Urology", confidence: "0.4"},
{ symptom: "nausea", specialty: "Gastroenterology", confidence: "0.8"},
{ symptom: "nausea", specialty: "Endocrinology", confidence: "0.4"},
{ symptom: "nausea", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "vomiting", specialty: "Gastroenterology", confidence: "0.8"},
{ symptom: "vomiting", specialty: "Infectious Disease", confidence: "0.6"},
{ symptom: "vomiting", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "persistentCough", specialty: "Pulmonary Medicine", confidence: "0.9"},
{ symptom: "persistentCough", specialty: "Infectious Disease", confidence: "0.6"},
{ symptom: "persistentCough", specialty: "Oncology", confidence: "0.3"},
{ symptom: "headache", specialty: "Neurology", confidence: "0.9"},
{ symptom: "headache", specialty: "Ophthalmology", confidence: "0.4"},
{ symptom: "headache", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "dizziness", specialty: "Neurology", confidence: "0.8"},
{ symptom: "dizziness", specialty: "Cardiovascular Medicine", confidence: "0.5"},
{ symptom: "dizziness", specialty: "Endocrinology", confidence: "0.4"},
{ symptom: "skinRash", specialty: "Dermatology", confidence: "0.9"},
{ symptom: "skinRash", specialty: "Allergy & Immunology", confidence: "0.6"},
{ symptom: "skinRash", specialty: "Infectious Disease", confidence: "0.4"},
{ symptom: "fever", specialty: "Infectious Disease", confidence: "0.9"},
{ symptom: "fever", specialty: "Primary Care", confidence: "0.7"},
{ symptom: "fever", specialty: "Hematology", confidence: "0.3"},
{ symptom: "fatigue", specialty: "Endocrinology", confidence: "0.7"},
{ symptom: "fatigue", specialty: "Primary Care", confidence: "0.7"},
{ symptom: "fatigue", specialty: "Hematology", confidence: "0.4"},
{ symptom: "jointPain", specialty: "Rheumatology", confidence: "0.9"},
{ symptom: "jointPain", specialty: "Orthopedics", confidence: "0.5"},
{ symptom: "jointPain", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "backPain", specialty: "Physical Medicine & Rehabilitation", confidence: "0.8"},
{ symptom: "backPain", specialty: "Neurosurgery", confidence: "0.6"},
{ symptom: "backPain", specialty: "Orthopedics", confidence: "0.5"},
{ symptom: "neckPain", specialty: "Physical Medicine & Rehabilitation", confidence: "0.8"},
{ symptom: "neckPain", specialty: "Orthopedics", confidence: "0.5"},
{ symptom: "neckPain", specialty: "Neurosurgery", confidence: "0.4"},
{ symptom: "frequentUrination", specialty: "Urology", confidence: "0.9"},
{ symptom: "frequentUrination", specialty: "Endocrinology", confidence: "0.6"},
{ symptom: "frequentUrination", specialty: "Nephrology", confidence: "0.5"},
{ symptom: "bloodInUrine", specialty: "Urology", confidence: "0.9"},
{ symptom: "bloodInUrine", specialty: "Nephrology", confidence: "0.7"},
{ symptom: "bloodInUrine", specialty: "Contact Centre", confidence: "0.8"},
{ symptom: "blurredVision", specialty: "Ophthalmology", confidence: "0.9"},
{ symptom: "blurredVision", specialty: "Endocrinology", confidence: "0.6"},
{ symptom: "blurredVision", specialty: "Neurology", confidence: "0.5"},
{ symptom: "swellingLegs", specialty: "Cardiovascular Medicine", confidence: "0.9"},
{ symptom: "swellingLegs", specialty: "Nephrology", confidence: "0.7"},
{ symptom: "swellingLegs", specialty: "Endocrinology", confidence: "0.4"},
{ symptom: "weightLoss", specialty: "Oncology", confidence: "0.8"},
{ symptom: "weightLoss", specialty: "Endocrinology", confidence: "0.7"},
{ symptom: "weightLoss", specialty: "Gastroenterology", confidence: "0.5"},
{ symptom: "weightGain", specialty: "Endocrinology", confidence: "0.9"},
{ symptom: "weightGain", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "chronicDiarrhea", specialty: "Gastroenterology", confidence: "0.9"},
{ symptom: "chronicDiarrhea", specialty: "Infectious Disease", confidence: "0.6"},
{ symptom: "chronicDiarrhea", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "constipation", specialty: "Gastroenterology", confidence: "0.9"},
{ symptom: "constipation", specialty: "General Surgery", confidence: "0.6"},
{ symptom: "constipation", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "lossOfAppetite", specialty: "Gastroenterology", confidence: "0.8"},
{ symptom: "lossOfAppetite", specialty: "Oncology", confidence: "0.7"},
{ symptom: "lossOfAppetite", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "palpitations", specialty: "Cardiovascular Medicine", confidence: "0.9"},
{ symptom: "palpitations", specialty: "Endocrinology", confidence: "0.6"},
{ symptom: "palpitations", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "legPain", specialty: "Vascular Surgery", confidence: "0.8"},
{ symptom: "legPain", specialty: "Orthopedics", confidence: "0.5"},
{ symptom: "legPain", specialty: "Physical Medicine & Rehabilitation", confidence: "0.5"},
{ symptom: "armWeakness", specialty: "Neurology", confidence: "0.9"},
{ symptom: "armWeakness", specialty: "Neurosurgery", confidence: "0.7"},
{ symptom: "armWeakness", specialty: "Emergency Medicine", confidence: "1.0"},
{ symptom: "difficultySwallowing", specialty: "Gastroenterology", confidence: "0.8"},
{ symptom: "difficultySwallowing", specialty: "Otolaryngology", confidence: "0.6"},
{ symptom: "difficultySwallowing", specialty: "Contact Centre", confidence: "0.9"},
{ symptom: "persistentFever", specialty: "Infectious Disease", confidence: "0.9"},
{ symptom: "persistentFever", specialty: "Oncology", confidence: "0.6"},
{ symptom: "persistentFever", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "numbness", specialty: "Neurology", confidence: "0.9"},
{ symptom: "numbness", specialty: "Neurosurgery", confidence: "0.6"},
{ symptom: "numbness", specialty: "Endocrinology", confidence: "0.4"},
{ symptom: "visionLoss", specialty: "Ophthalmology", confidence: "0.9"},
{ symptom: "visionLoss", specialty: "Neurology", confidence: "0.7"},
{ symptom: "visionLoss", specialty: "Emergency Medicine", confidence: "1.0"},
{ symptom: "hearingLoss", specialty: "Otolaryngology", confidence: "0.9"},
{ symptom: "hearingLoss", specialty: "Neurology", confidence: "0.6"},
{ symptom: "hearingLoss", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "noseBleed", specialty: "Otolaryngology", confidence: "0.9"},
{ symptom: "noseBleed", specialty: "Hematology", confidence: "0.6"},
{ symptom: "noseBleed", specialty: "Contact Centre", confidence: "0.8"},
{ symptom: "bleedingGums", specialty: "Dentistry", confidence: "0.9"},
{ symptom: "bleedingGums", specialty: "Hematology", confidence: "0.6"},
{ symptom: "bleedingGums", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "toothPain", specialty: "Dentistry", confidence: "0.9"},
{ symptom: "toothPain", specialty: "Otolaryngology", confidence: "0.5"},
{ symptom: "toothPain", specialty: "Contact Centre", confidence: "0.2"},
{ symptom: "breastLump", specialty: "Breast Surgery", confidence: "0.9"},
{ symptom: "breastLump", specialty: "Oncology", confidence: "0.8"},
{ symptom: "breastLump", specialty: "Gynecology", confidence: "0.4"},
{ symptom: "pelvicPain", specialty: "Gynecology", confidence: "0.9"},
{ symptom: "pelvicPain", specialty: "Urology", confidence: "0.6"},
{ symptom: "pelvicPain", specialty: "Gastroenterology", confidence: "0.5"},
{ symptom: "irregularPeriods", specialty: "Gynecology", confidence: "0.9"},
{ symptom: "irregularPeriods", specialty: "Endocrinology", confidence: "0.6"},
{ symptom: "irregularPeriods", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "infertility", specialty: "Gynecology", confidence: "0.9"},
{ symptom: "infertility", specialty: "Endocrinology", confidence: "0.7"},
{ symptom: "infertility", specialty: "Urology", confidence: "0.4"},
{ symptom: "eyePain", specialty: "Ophthalmology", confidence: "0.9"},
{ symptom: "eyePain", specialty: "Neurology", confidence: "0.6"},
{ symptom: "eyePain", specialty: "Contact Centre", confidence: "0.8"},
{ symptom: "redEye", specialty: "Ophthalmology", confidence: "0.9"},
{ symptom: "redEye", specialty: "Infectious Disease", confidence: "0.5"},
{ symptom: "redEye", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "earPain", specialty: "Otolaryngology", confidence: "0.9"},
{ symptom: "earPain", specialty: "Dentistry", confidence: "0.5"},
{ symptom: "earPain", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "snoring", specialty: "Otolaryngology", confidence: "0.8"},
{ symptom: "snoring", specialty: "Pulmonary Medicine", confidence: "0.6"},
{ symptom: "snoring", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "chronicFatigue", specialty: "Endocrinology", confidence: "0.8"},
{ symptom: "chronicFatigue", specialty: "Hematology", confidence: "0.5"},
{ symptom: "chronicFatigue", specialty: "Primary Care", confidence: "0.7"},
{ symptom: "swellingHands", specialty: "Rheumatology", confidence: "0.8"},
{ symptom: "swellingHands", specialty: "Vascular Surgery", confidence: "0.5"},
{ symptom: "swellingHands", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "handTremor", specialty: "Neurology", confidence: "0.9"},
{ symptom: "handTremor", specialty: "Endocrinology", confidence: "0.5"},
{ symptom: "handTremor", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "lossOfBalance", specialty: "Neurology", confidence: "0.9"},
{ symptom: "lossOfBalance", specialty: "Physical Medicine & Rehabilitation", confidence: "0.6"},
{ symptom: "lossOfBalance", specialty: "Emergency Medicine", confidence: "1.0"},
{ symptom: "memoryIssues", specialty: "Neurology", confidence: "0.8"},
{ symptom: "memoryIssues", specialty: "Endocrinology", confidence: "0.4"},
{ symptom: "memoryIssues", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "excessiveThirst", specialty: "Endocrinology", confidence: "0.9"},
{ symptom: "excessiveThirst", specialty: "Nephrology", confidence: "0.5"},
{ symptom: "excessiveThirst", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "swollenLymphNodes", specialty: "Hematology", confidence: "0.8"},
{ symptom: "swollenLymphNodes", specialty: "Infectious Disease", confidence: "0.6"},
{ symptom: "swollenLymphNodes", specialty: "Oncology", confidence: "0.5"},
{ symptom: "bruisingEasily", specialty: "Hematology", confidence: "0.9"},
{ symptom: "bruisingEasily", specialty: "Oncology", confidence: "0.5"},
{ symptom: "bruisingEasily", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "yellowSkin", specialty: "Hepatology", confidence: "0.9"},
{ symptom: "yellowSkin", specialty: "Gastroenterology", confidence: "0.7"},
{ symptom: "yellowSkin", specialty: "Contact Centre", confidence: "0.8"},
{ symptom: "coldHandsFeet", specialty: "Vascular Surgery", confidence: "0.8"},
{ symptom: "coldHandsFeet", specialty: "Cardiovascular Medicine", confidence: "0.6"},
{ symptom: "coldHandsFeet", specialty: "Endocrinology", confidence: "0.4"},
{ symptom: "sleepApnea", specialty: "Pulmonary Medicine", confidence: "0.9"},
{ symptom: "sleepApnea", specialty: "Otolaryngology", confidence: "0.7"},
{ symptom: "sleepApnea", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "swollenAbdomen", specialty: "Gastroenterology", confidence: "0.9"},
{ symptom: "swollenAbdomen", specialty: "Hepatology", confidence: "0.7"},
{ symptom: "swollenAbdomen", specialty: "Oncology", confidence: "0.5"},
{ symptom: "bloodInStool", specialty: "Gastroenterology", confidence: "0.9"},
{ symptom: "bloodInStool", specialty: "Colorectal Surgery", confidence: "0.8"},
{ symptom: "bloodInStool", specialty: "Contact Centre", confidence: "1.0"},
{ symptom: "rectalBleeding", specialty: "Colorectal Surgery", confidence: "0.9"},
{ symptom: "rectalBleeding", specialty: "Gastroenterology", confidence: "0.8"},
{ symptom: "rectalBleeding", specialty: "Contact Centre", confidence: "1.0"},
{ symptom: "legCramping", specialty: "Vascular Surgery", confidence: "0.8"},
{ symptom: "legCramping", specialty: "Cardiovascular Medicine", confidence: "0.6"},
{ symptom: "legCramping", specialty: "Primary Care", confidence: "0.5"},
{ symptom: "legSwelling", specialty: "Cardiovascular Medicine", confidence: "0.8"},
{ symptom: "fainting", specialty: "Cardiovascular Medicine", confidence: "0.85"},
{ symptom: "fatigue", specialty: "Cardiovascular Medicine", confidence: "0.7"},
{ symptom: "chronicCough", specialty: "Pulmonary Medicine", confidence: "0.8"},
{ symptom: "wheezing", specialty: "Pulmonary Medicine", confidence: "0.75"},
{ symptom: "coughWithPhlegm", specialty: "Pulmonary Medicine", confidence: "0.85"},
{ symptom: "chestTightness", specialty: "Pulmonary Medicine", confidence: "0.8"},
{ symptom: "heartburn", specialty: "Gastroenterology", confidence: "0.8"},
{ symptom: "diarrhea", specialty: "Gastroenterology", confidence: "0.85"},
{ symptom: "bloating", specialty: "Gastroenterology", confidence: "0.7"},
{ symptom: "seizure", specialty: "Neurology", confidence: "0.85"},
{ symptom: "memoryLoss", specialty: "Neurology", confidence: "0.85"},
{ symptom: "weakness", specialty: "Neurology", confidence: "0.8"},
{ symptom: "tremor", specialty: "Neurology", confidence: "0.7"},
{ symptom: "musclePain", specialty: "Rheumatology", confidence: "0.8"},
{ symptom: "stiffness", specialty: "Rheumatology", confidence: "0.75"},
{ symptom: "swollenJoints", specialty: "Rheumatology", confidence: "0.85"},
{ symptom: "backPain", specialty: "Rheumatology", confidence: "0.8"},
{ symptom: "fatigue", specialty: "Rheumatology", confidence: "0.7"},
{ symptom: "itching", specialty: "Dermatology", confidence: "0.8"},
{ symptom: "acne", specialty: "Dermatology", confidence: "0.7"},
{ symptom: "hairLoss", specialty: "Dermatology", confidence: "0.7"},
{ symptom: "eczema", specialty: "Dermatology", confidence: "0.8"},
{ symptom: "psoriasis", specialty: "Dermatology", confidence: "0.85"},
{ symptom: "depression", specialty: "Psychiatry", confidence: "0.9"},
{ symptom: "anxiety", specialty: "Psychiatry", confidence: "0.9"},
{ symptom: "insomnia", specialty: "Psychiatry", confidence: "0.8"},
{ symptom: "panicAttacks", specialty: "Psychiatry", confidence: "0.85"},
{ symptom: "hallucinations", specialty: "Psychiatry", confidence: "0.9"},
{ symptom: "moodSwings", specialty: "Psychiatry", confidence: "0.8"},
{ symptom: "painfulUrination", specialty: "Urology", confidence: "0.8"},
{ symptom: "incontinence", specialty: "Urology", confidence: "0.8"},
{ symptom: "difficultyUrinating", specialty: "Urology", confidence: "0.85"}];
