const quizData = [
{ location: "chest", symptom: "chest pain", specialty: "Cardiovascular Medicine", confidence: "0.9"},
{ location: "chest", symptom: "chest pain", specialty: "Pulmonary Medicine", confidence: "0.4"},
{ location: "chest", symptom: "chest pain", specialty: "Gastroenterology", confidence: "0.3"},
{ location: "chest", symptom: "chest pain", specialty: "Contact Centre", confidence: "1.0"},
{ location: "chest", symptom: "shortness of breath", specialty: "Pulmonary Medicine", confidence: "0.9"},
{ location: "chest", symptom: "shortness of breath", specialty: "Cardiovascular Medicine", confidence: "0.8"},
{ location: "chest", symptom: "shortness of breath", specialty: "Emergency Medicine", confidence: "1.0"},
{ location: "abdomin", symptom: "abdominal pain", specialty: "Gastroenterology", confidence: "0.9"},
{ location: "abdomin", symptom: "abdominal pain", specialty: "General Surgery", confidence: "0.7"},
{ location: "abdomin", symptom: "abdominal pain", specialty: "Gynecology", confidence: "0.4"},
{ location: "abdomin", symptom: "abdominal pain", specialty: "Urology", confidence: "0.4"},
{ location: "head", symptom: "nausea", specialty: "Gastroenterology", confidence: "0.8"},
{ location: "head", symptom: "nausea", specialty: "Endocrinology", confidence: "0.4"},
{ location: "head", symptom: "nausea", specialty: "Primary Care", confidence: "0.5"},
{ location: "abdomin", symptom: "vomiting", specialty: "Gastroenterology", confidence: "0.8"},
{ location: "abdomin", symptom: "vomiting", specialty: "Infectious Disease", confidence: "0.6"},
{ location: "abdomin", symptom: "vomiting", specialty: "Primary Care", confidence: "0.5"},
{ location: "chest", symptom: "persistent cough", specialty: "Pulmonary Medicine", confidence: "0.9"},
{ location: "chest", symptom: "persistent cough", specialty: "Infectious Disease", confidence: "0.6"},
{ location: "chest", symptom: "persistent cough", specialty: "Oncology", confidence: "0.3"},
{ location: "head", symptom: "headache", specialty: "Neurology", confidence: "0.9"},
{ location: "head", symptom: "headache", specialty: "Ophthalmology", confidence: "0.4"},
{ location: "head", symptom: "headache", specialty: "Primary Care", confidence: "0.5"},
{ location: "head", symptom: "dizziness", specialty: "Neurology", confidence: "0.8"},
{ location: "head", symptom: "dizziness", specialty: "Cardiovascular Medicine", confidence: "0.5"},
{ location: "head", symptom: "dizziness", specialty: "Endocrinology", confidence: "0.4"},
{ location: "skin", symptom: "rash", specialty: "Dermatology", confidence: "0.9"},
{ location: "skin", symptom: "rash", specialty: "Allergy & Immunology", confidence: "0.6"},
{ location: "skin", symptom: "rash", specialty: "Infectious Disease", confidence: "0.4"},
{ location: "head", symptom: "fever", specialty: "Infectious Disease", confidence: "0.9"},
{ location: "head", symptom: "fever", specialty: "Primary Care", confidence: "0.7"},
{ location: "head", symptom: "fever", specialty: "Hematology", confidence: "0.3"},
{ location: "other", symptom: "fatigue", specialty: "Endocrinology", confidence: "0.7"},
{ location: "other", symptom: "fatigue", specialty: "Primary Care", confidence: "0.7"},
{ location: "other", symptom: "fatigue", specialty: "Hematology", confidence: "0.4"},
{ location: "joints", symptom: "joints pain", specialty: "Rheumatology", confidence: "0.9"},
{ location: "joints", symptom: "joints pain", specialty: "Orthopedics", confidence: "0.5"},
{ location: "joints", symptom: "joints pain", specialty: "Primary Care", confidence: "0.5"},
{ location: "back", symptom: "back pain", specialty: "Physical Medicine & Rehabilitation", confidence: "0.8"},
{ location: "back", symptom: "back pain", specialty: "Neurosurgery", confidence: "0.6"},
{ location: "back", symptom: "back pain", specialty: "Orthopedics", confidence: "0.5"},
{ location: "neck", symptom: "neck pain", specialty: "Physical Medicine & Rehabilitation", confidence: "0.8"},
{ location: "neck", symptom: "neck pain", specialty: "Orthopedics", confidence: "0.5"},
{ location: "neck", symptom: "neck pain", specialty: "Neurosurgery", confidence: "0.4"},
{ location: "other", symptom: "frequent urination", specialty: "Urology", confidence: "0.9"},
{ location: "other", symptom: "frequent urination", specialty: "Endocrinology", confidence: "0.6"},
{ location: "other", symptom: "frequent urination", specialty: "Nephrology", confidence: "0.5"},
{ location: "other", symptom: "blood in urine", specialty: "Urology", confidence: "0.9"},
{ location: "other", symptom: "blood in urine", specialty: "Nephrology", confidence: "0.7"},
{ location: "other", symptom: "blood in urine", specialty: "Contact Centre", confidence: "0.8"},
{ location: "eyes", symptom: "blurred vision", specialty: "Ophthalmology", confidence: "0.9"},
{ location: "eyes", symptom: "blurred vision", specialty: "Endocrinology", confidence: "0.6"},
{ location: "eyes", symptom: "blurred vision", specialty: "Neurology", confidence: "0.5"},
{ location: "legs", symptom: "legs swelling", specialty: "Cardiovascular Medicine", confidence: "0.9"},
{ location: "legs", symptom: "legs swelling", specialty: "Nephrology", confidence: "0.7"},
{ location: "legs", symptom: "legs swelling", specialty: "Endocrinology", confidence: "0.4"},
{ location: "other", symptom: "weight loss", specialty: "Oncology", confidence: "0.8"},
{ location: "other", symptom: "weight loss", specialty: "Endocrinology", confidence: "0.7"},
{ location: "other", symptom: "weight loss", specialty: "Gastroenterology", confidence: "0.5"},
{ location: "other", symptom: "weight gain", specialty: "Endocrinology", confidence: "0.9"},
{ location: "other", symptom: "weight gain", specialty: "Primary Care", confidence: "0.5"},
{ location: "abdomin", symptom: "chronic diarrhea", specialty: "Gastroenterology", confidence: "0.9"},
{ location: "abdomin", symptom: "chronic diarrhea", specialty: "Infectious Disease", confidence: "0.6"},
{ location: "abdomin", symptom: "chronic diarrhea", specialty: "Primary Care", confidence: "0.5"},
{ location: "abdomin", symptom: "constipation", specialty: "Gastroenterology", confidence: "0.9"},
{ location: "abdomin", symptom: "constipation", specialty: "General Surgery", confidence: "0.6"},
{ location: "abdomin", symptom: "constipation", specialty: "Primary Care", confidence: "0.5"},
{ location: "abdomin", symptom: "loss of appetite", specialty: "Gastroenterology", confidence: "0.8"},
{ location: "abdomin", symptom: "loss of appetite", specialty: "Oncology", confidence: "0.7"},
{ location: "abdomin", symptom: "loss of appetite", specialty: "Primary Care", confidence: "0.5"},
{ location: "chest", symptom: "palpitations", specialty: "Cardiovascular Medicine", confidence: "0.9"},
{ location: "chest", symptom: "palpitations", specialty: "Endocrinology", confidence: "0.6"},
{ location: "chest", symptom: "palpitations", specialty: "Primary Care", confidence: "0.5"},
{ location: "legs", symptom: "legs pain", specialty: "Vascular Surgery", confidence: "0.8"},
{ location: "legs", symptom: "legs pain", specialty: "Orthopedics", confidence: "0.5"},
{ location: "legs", symptom: "legs pain", specialty: "Physical Medicine & Rehabilitation", confidence: "0.5"},
{ location: "arms", symptom: "arms weakness", specialty: "Neurology", confidence: "0.9"},
{ location: "arms", symptom: "arms weakness", specialty: "Neurosurgery", confidence: "0.7"},
{ location: "arms", symptom: "arms weakness", specialty: "Emergency Medicine", confidence: "1.0"},
{ location: "mouth/throat", symptom: "difficulty swallowing", specialty: "Gastroenterology", confidence: "0.8"},
{ location: "mouth/throat", symptom: "difficulty swallowing", specialty: "Otolaryngology", confidence: "0.6"},
{ location: "mouth/throat", symptom: "difficulty swallowing", specialty: "Contact Centre", confidence: "0.9"},
{ location: "other", symptom: "persistent fever", specialty: "Infectious Disease", confidence: "0.9"},
{ location: "other", symptom: "persistent fever", specialty: "Oncology", confidence: "0.6"},
{ location: "other", symptom: "persistent fever", specialty: "Primary Care", confidence: "0.5"},
{ location: "abdomin", symptom: "numbness", specialty: "Neurology", confidence: "0.9"},
{ location: "abdomin", symptom: "numbness", specialty: "Neurosurgery", confidence: "0.6"},
{ location: "abdomin", symptom: "numbness", specialty: "Endocrinology", confidence: "0.4"},
{ location: "eyes", symptom: "vision loss", specialty: "Ophthalmology", confidence: "0.9"},
{ location: "eyes", symptom: "vision loss", specialty: "Neurology", confidence: "0.7"},
{ location: "eyes", symptom: "vision loss", specialty: "Emergency Medicine", confidence: "1.0"},
{ location: "ears", symptom: "hearing loss", specialty: "Otolaryngology", confidence: "0.9"},
{ location: "ears", symptom: "hearing loss", specialty: "Neurology", confidence: "0.6"},
{ location: "ears", symptom: "hearing loss", specialty: "Primary Care", confidence: "0.5"},
{ location: "head", symptom: "nose bleed", specialty: "Otolaryngology", confidence: "0.9"},
{ location: "head", symptom: "nose bleed", specialty: "Hematology", confidence: "0.6"},
{ location: "head", symptom: "nose bleed", specialty: "Contact Centre", confidence: "0.8"},
{ location: "mouth/throat", symptom: "bleeding gums", specialty: "Dentistry", confidence: "0.9"},
{ location: "mouth/throat", symptom: "bleeding gums", specialty: "Hematology", confidence: "0.6"},
{ location: "mouth/throat", symptom: "bleeding gums", specialty: "Primary Care", confidence: "0.5"},
{ location: "mouth/throat", symptom: "tooth pain", specialty: "Dentistry", confidence: "0.9"},
{ location: "mouth/throat", symptom: "tooth pain", specialty: "Otolaryngology", confidence: "0.5"},
{ location: "mouth/throat", symptom: "tooth pain", specialty: "Contact Centre", confidence: "0.2"},
{ location: "chest", symptom: "breast lump", specialty: "Breast Surgery", confidence: "0.9"},
{ location: "chest", symptom: "breast lump", specialty: "Oncology", confidence: "0.8"},
{ location: "chest", symptom: "breast lump", specialty: "Gynecology", confidence: "0.4"},
{ location: "other", symptom: "pelvic pain", specialty: "Gynecology", confidence: "0.9"},
{ location: "other", symptom: "pelvic pain", specialty: "Urology", confidence: "0.6"},
{ location: "other", symptom: "pelvic pain", specialty: "Gastroenterology", confidence: "0.5"},
{ location: "other", symptom: "irregular periods", specialty: "Gynecology", confidence: "0.9"},
{ location: "other", symptom: "irregular periods", specialty: "Endocrinology", confidence: "0.6"},
{ location: "other", symptom: "irregular periods", specialty: "Primary Care", confidence: "0.5"},
{ location: "other", symptom: "infertility", specialty: "Gynecology", confidence: "0.9"},
{ location: "other", symptom: "infertility", specialty: "Endocrinology", confidence: "0.7"},
{ location: "other", symptom: "infertility", specialty: "Urology", confidence: "0.4"},
{ location: "eyes", symptom: "eye pain", specialty: "Ophthalmology", confidence: "0.9"},
{ location: "eyes", symptom: "eye pain", specialty: "Neurology", confidence: "0.6"},
{ location: "eyes", symptom: "eye pain", specialty: "Contact Centre", confidence: "0.8"},
{ location: "eyes", symptom: "red eye", specialty: "Ophthalmology", confidence: "0.9"},
{ location: "eyes", symptom: "red eye", specialty: "Infectious Disease", confidence: "0.5"},
{ location: "eyes", symptom: "red eye", specialty: "Primary Care", confidence: "0.5"},
{ location: "ears", symptom: "ear pain", specialty: "Otolaryngology", confidence: "0.9"},
{ location: "ears", symptom: "ear pain", specialty: "Dentistry", confidence: "0.5"},
{ location: "ears", symptom: "ear pain", specialty: "Primary Care", confidence: "0.5"},
{ location: "chest", symptom: "snoring", specialty: "Otolaryngology", confidence: "0.8"},
{ location: "chest", symptom: "snoring", specialty: "Pulmonary Medicine", confidence: "0.6"},
{ location: "chest", symptom: "snoring", specialty: "Primary Care", confidence: "0.5"},
{ location: "other", symptom: "chronic fatigue", specialty: "Endocrinology", confidence: "0.8"},
{ location: "other", symptom: "chronic fatigue", specialty: "Hematology", confidence: "0.5"},
{ location: "other", symptom: "chronic fatigue", specialty: "Primary Care", confidence: "0.7"},
{ location: "arms", symptom: "swelling hands", specialty: "Rheumatology", confidence: "0.8"},
{ location: "arms", symptom: "swelling hands", specialty: "Vascular Surgery", confidence: "0.5"},
{ location: "arms", symptom: "swelling hands", specialty: "Primary Care", confidence: "0.5"},
{ location: "arms", symptom: "hand tremor", specialty: "Neurology", confidence: "0.9"},
{ location: "arms", symptom: "hand tremor", specialty: "Endocrinology", confidence: "0.5"},
{ location: "arms", symptom: "hand tremor", specialty: "Primary Care", confidence: "0.5"},
{ location: "other", symptom: "loss of balance", specialty: "Neurology", confidence: "0.9"},
{ location: "other", symptom: "loss of balance", specialty: "Physical Medicine & Rehabilitation", confidence: "0.6"},
{ location: "other", symptom: "loss of balance", specialty: "Emergency Medicine", confidence: "1.0"},
{ location: "head", symptom: "memory issues", specialty: "Neurology", confidence: "0.8"},
{ location: "head", symptom: "memory issues", specialty: "Endocrinology", confidence: "0.4"},
{ location: "head", symptom: "memory issues", specialty: "Primary Care", confidence: "0.5"},
{ location: "mouth/throat", symptom: "excessive thirst", specialty: "Endocrinology", confidence: "0.9"},
{ location: "mouth/throat", symptom: "excessive thirst", specialty: "Nephrology", confidence: "0.5"},
{ location: "mouth/throat", symptom: "excessive thirst", specialty: "Primary Care", confidence: "0.5"},
{ location: "skin", symptom: "bruising easily", specialty: "Hematology", confidence: "0.9"},
{ location: "skin", symptom: "bruising easily", specialty: "Oncology", confidence: "0.5"},
{ location: "skin", symptom: "bruising easily", specialty: "Primary Care", confidence: "0.5"},
{ location: "skin", symptom: "yellow skin", specialty: "Hepatology", confidence: "0.9"},
{ location: "skin", symptom: "yellow skin", specialty: "Gastroenterology", confidence: "0.7"},
{ location: "skin", symptom: "yellow skin", specialty: "Contact Centre", confidence: "0.8"},
{ location: "other", symptom: "cold hands and feet", specialty: "Vascular Surgery", confidence: "0.8"},
{ location: "other", symptom: "cold hands and feet", specialty: "Cardiovascular Medicine", confidence: "0.6"},
{ location: "other", symptom: "cold hands and feet", specialty: "Endocrinology", confidence: "0.4"},
{ location: "other", symptom: "sleep apnea", specialty: "Pulmonary Medicine", confidence: "0.9"},
{ location: "other", symptom: "sleep apnea", specialty: "Otolaryngology", confidence: "0.7"},
{ location: "other", symptom: "sleep apnea", specialty: "Primary Care", confidence: "0.5"},
{ location: "abdomin", symptom: "swollen abdomen", specialty: "Gastroenterology", confidence: "0.9"},
{ location: "abdomin", symptom: "swollen abdomen", specialty: "Hepatology", confidence: "0.7"},
{ location: "abdomin", symptom: "swollen abdomen", specialty: "Oncology", confidence: "0.5"},
{ location: "other", symptom: "blood in stool", specialty: "Gastroenterology", confidence: "0.9"},
{ location: "other", symptom: "blood in stool", specialty: "Colorectal Surgery", confidence: "0.8"},
{ location: "other", symptom: "blood in stool", specialty: "Contact Centre", confidence: "1.0"},
{ location: "other", symptom: "rectal bleeding", specialty: "Colorectal Surgery", confidence: "0.9"},
{ location: "other", symptom: "rectal bleeding", specialty: "Gastroenterology", confidence: "0.8"},
{ location: "other", symptom: "rectal bleeding", specialty: "Contact Centre", confidence: "1.0"},
{ location: "legs", symptom: "leg cramping", specialty: "Vascular Surgery", confidence: "0.8"},
{ location: "legs", symptom: "leg cramping", specialty: "Cardiovascular Medicine", confidence: "0.6"},
{ location: "legs", symptom: "leg cramping", specialty: "Primary Care", confidence: "0.5"},
{ location: "legs", symptom: "leg swelling", specialty: "Cardiovascular Medicine", confidence: "0.8"},
{ location: "other", symptom: "fainting", specialty: "Cardiovascular Medicine", confidence: "0.85"},
{ location: "other", symptom: "fatigue", specialty: "Cardiovascular Medicine", confidence: "0.7"},
{ location: "chest", symptom: "chronic cough", specialty: "Pulmonary Medicine", confidence: "0.8"},
{ location: "chest", symptom: "wheezing", specialty: "Pulmonary Medicine", confidence: "0.75"},
{ location: "chest", symptom: "cough with phlegm", specialty: "Pulmonary Medicine", confidence: "0.85"},
{ location: "chest", symptom: "chest tightness", specialty: "Pulmonary Medicine", confidence: "0.8"},
{ location: "chest", symptom: "heartburn", specialty: "Gastroenterology", confidence: "0.8"},
{ location: "abdomin", symptom: "diarrhea", specialty: "Gastroenterology", confidence: "0.85"},
{ location: "abdomin", symptom: "bloating", specialty: "Gastroenterology", confidence: "0.7"},
{ location: "other", symptom: "seizure", specialty: "Neurology", confidence: "0.85"},
{ location: "other", symptom: "tremor", specialty: "Neurology", confidence: "0.7"},
{ location: "other", symptom: "muscle pain", specialty: "Rheumatology", confidence: "0.8"},
{ location: "other", symptom: "stiffness", specialty: "Rheumatology", confidence: "0.75"},
{ location: "joints", symptom: "swollen joints", specialty: "Rheumatology", confidence: "0.85"},
{ location: "back", symptom: "back pain", specialty: "Rheumatology", confidence: "0.8"},
{ location: "other", symptom: "fatigue", specialty: "Rheumatology", confidence: "0.7"},
{ location: "skin", symptom: "itching", specialty: "Dermatology", confidence: "0.8"},
{ location: "skin", symptom: "acne", specialty: "Dermatology", confidence: "0.7"},
{ location: "other", symptom: "hair loss", specialty: "Dermatology", confidence: "0.7"},
{ location: "other", symptom: "depression", specialty: "Psychiatry", confidence: "0.9"},
{ location: "other", symptom: "anxiety", specialty: "Psychiatry", confidence: "0.9"},
{ location: "other", symptom: "insomnia", specialty: "Psychiatry", confidence: "0.8"},
{ location: "other", symptom: "panic attacks", specialty: "Psychiatry", confidence: "0.85"},
{ location: "other", symptom: "hallucinations", specialty: "Psychiatry", confidence: "0.9"},
{ location: "other", symptom: "mood swings", specialty: "Psychiatry", confidence: "0.8"},
{ location: "other", symptom: "incontinence", specialty: "Urology", confidence: "0.8"},
{ location: "other", symptom: "difficulty urinating", specialty: "Urology", confidence: "0.85"}];
